[2025-09-08T18:27:17.099+0000] {processor.py:186} INFO - Started process (PID=46905) to work on /opt/airflow/dags/5_transposition.py
[2025-09-08T18:27:17.099+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/5_transposition.py for tasks to queue
[2025-09-08T18:27:17.102+0000] {logging_mixin.py:190} INFO - [2025-09-08T18:27:17.101+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/5_transposition.py
[2025-09-08T18:27:17.594+0000] {logging_mixin.py:190} INFO - [2025-09-08T18:27:17.592+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/5_transposition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/5_transposition.py", line 167, in <module>
    fetch_data >> resolve >> upload_results
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 263, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'update_relative'
[2025-09-08T18:27:17.594+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/5_transposition.py
[2025-09-08T18:27:17.602+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/5_transposition.py took 0.507 seconds
[2025-09-08T19:23:33.117+0000] {processor.py:186} INFO - Started process (PID=46978) to work on /opt/airflow/dags/5_transposition.py
[2025-09-08T19:23:33.119+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/5_transposition.py for tasks to queue
[2025-09-08T19:23:33.122+0000] {logging_mixin.py:190} INFO - [2025-09-08T19:23:33.122+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/5_transposition.py
[2025-09-08T19:23:33.721+0000] {logging_mixin.py:190} INFO - [2025-09-08T19:23:33.713+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/5_transposition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/5_transposition.py", line 167, in <module>
    fetch_data >> resolve >> upload_results
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 263, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'update_relative'
[2025-09-08T19:23:33.721+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/5_transposition.py
[2025-09-08T19:23:33.731+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/5_transposition.py took 0.624 seconds
[2025-09-08T20:47:07.212+0000] {processor.py:186} INFO - Started process (PID=47051) to work on /opt/airflow/dags/5_transposition.py
[2025-09-08T20:47:07.212+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/5_transposition.py for tasks to queue
[2025-09-08T20:47:07.214+0000] {logging_mixin.py:190} INFO - [2025-09-08T20:47:07.213+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/5_transposition.py
[2025-09-08T20:47:07.762+0000] {logging_mixin.py:190} INFO - [2025-09-08T20:47:07.756+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/5_transposition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/5_transposition.py", line 167, in <module>
    fetch_data >> resolve >> upload_results
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 263, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'update_relative'
[2025-09-08T20:47:07.762+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/5_transposition.py
[2025-09-08T20:47:07.770+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/5_transposition.py took 0.563 seconds
[2025-09-08T22:21:42.168+0000] {processor.py:186} INFO - Started process (PID=47124) to work on /opt/airflow/dags/5_transposition.py
[2025-09-08T22:21:42.169+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/5_transposition.py for tasks to queue
[2025-09-08T22:21:42.171+0000] {logging_mixin.py:190} INFO - [2025-09-08T22:21:42.171+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/5_transposition.py
[2025-09-08T22:21:42.715+0000] {logging_mixin.py:190} INFO - [2025-09-08T22:21:42.713+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/5_transposition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/5_transposition.py", line 167, in <module>
    fetch_data >> resolve >> upload_results
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 263, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'update_relative'
[2025-09-08T22:21:42.716+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/5_transposition.py
[2025-09-08T22:21:42.729+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/5_transposition.py took 0.566 seconds
[2025-09-08T23:42:14.089+0000] {processor.py:186} INFO - Started process (PID=47197) to work on /opt/airflow/dags/5_transposition.py
[2025-09-08T23:42:14.090+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/5_transposition.py for tasks to queue
[2025-09-08T23:42:14.093+0000] {logging_mixin.py:190} INFO - [2025-09-08T23:42:14.092+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/5_transposition.py
[2025-09-08T23:42:14.836+0000] {logging_mixin.py:190} INFO - [2025-09-08T23:42:14.832+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/5_transposition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/5_transposition.py", line 167, in <module>
    fetch_data >> resolve >> upload_results
    ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 263, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 215, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'update_relative'
[2025-09-08T23:42:14.837+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/5_transposition.py
[2025-09-08T23:42:14.856+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/5_transposition.py took 0.771 seconds
